@echo off
echo Starting Backend Server...
cd backend
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Uvicorn...
python -m uvicorn app.main:app --reload --host 127.0.0.1 --port 8000
pause
